### ISSUE TITLE
A logo for you lib.

### ISSUE THREAD

**Issue by lexrus** [nixzhu/Wormhole#1]
<img src="https://cloud.githubusercontent.com/assets/219689/7840495/2fbfab00-04ca-11e5-9408-a6ec5ed44639.png" alt="logo" width="256"/>

And a banner for README.md:
![wormholebanner 2x](https://cloud.githubusercontent.com/assets/219689/7840490/292339ec-04ca-11e5-9a01-a64f54e72701.png)

**Comment by nixzhu** [comment]
Thanks!
